#!/usr/bin/env python
"""
Script to run generated visualization code from the benchmark.
Executes viz_*.py files from benchmarks/viz_results/generated_code/
"""

import sys
import subprocess
from pathlib import Path
from typing import List


def get_generated_files() -> List[Path]:
    """Get all generated visualization files."""
    code_dir = Path('benchmarks/viz_results/generated_code')
    if not code_dir.exists():
        print(f"Error: Directory not found: {code_dir}")
        return []
    
    files = sorted(code_dir.glob('viz_*.py'))
    return files


def run_visualization(file_path: Path) -> bool:
    """
    Run a single visualization file using the wrapper script.
    Returns True if successful, False otherwise.
    """
    print(f"\n{'='*70}")
    print(f"Running: {file_path.name}")
    print(f"{'='*70}")
    
    try:
        result = subprocess.run(
            [sys.executable, 'run_viz_code.py', str(file_path)],
            capture_output=False,
            text=True,
            timeout=60
        )
        success = result.returncode == 0
        status = "✓ SUCCESS" if success else "✗ FAILED"
        print(f"\n{status}: {file_path.name}")
        return success
    except subprocess.TimeoutExpired:
        print(f"\n✗ TIMEOUT: {file_path.name} (took > 60s)")
        return False
    except Exception as e:
        print(f"\n✗ ERROR: {file_path.name}")
        print(f"  {type(e).__name__}: {e}")
        return False


def main():
    """Main menu for running generated visualizations."""
    print("\n" + "╔" + "=" * 68 + "╗")
    print("║" + " RUN GENERATED VISUALIZATIONS ".center(68) + "║")
    print("║" + "─" * 68 + "║")
    print("║" + "This tool runs the code generated by the Visualization Agent".ljust(68) + "║")
    print("║" + " " * 68 + "║")
    print("╚" + "=" * 68 + "╝")
    
    # Get generated files
    generated_files = get_generated_files()
    
    if not generated_files:
        print("\nNo generated visualization files found.")
        print(f"Expected location: benchmarks/viz_results/generated_code/")
        return 1
    
    print(f"\nFound {len(generated_files)} generated visualization(s):\n")
    for i, file in enumerate(generated_files, 1):
        print(f"  {i}. {file.name}")
    
    # Menu loop
    while True:
        print("\n" + "=" * 70)
        print("Options:")
        print(f"  1. Run all ({len(generated_files)} files)")
        print("  2. Run specific visualization")
        print("  3. List generated files")
        print("  0. Exit")
        print("=" * 70)
        
        choice = input("\nEnter your choice (0-3): ").strip()
        
        if choice == "0":
            print("Exiting. Goodbye!")
            break
        
        elif choice == "1":
            print(f"\nRunning all {len(generated_files)} visualizations...\n")
            results = []
            for file in generated_files:
                success = run_visualization(file)
                results.append((file.name, success))
            
            # Summary
            print("\n" + "=" * 70)
            print("SUMMARY")
            print("=" * 70)
            success_count = sum(1 for _, success in results if success)
            print(f"Total: {len(results)}")
            print(f"Success: {success_count}/{len(results)}")
            print(f"Failed: {len(results) - success_count}/{len(results)}\n")
            for name, success in results:
                status = "✓" if success else "✗"
                print(f"  {status} {name}")
        
        elif choice == "2":
            print("\nSelect a visualization to run:")
            for i, file in enumerate(generated_files, 1):
                print(f"  {i}. {file.name}")
            print("  0. Back to menu")
            
            file_choice = input("\nEnter file number (0 to cancel): ").strip()
            try:
                file_idx = int(file_choice) - 1
                if file_idx == -1:
                    continue
                if 0 <= file_idx < len(generated_files):
                    file = generated_files[file_idx]
                    run_visualization(file)
                    
                    # Ask if they want to view the generated images
                    reports_dir = Path('reports')
                    if reports_dir.exists():
                        images = sorted(reports_dir.glob('visualization-*.png')) + sorted(reports_dir.glob('*_*.png'))
                        if images:
                            print(f"\nGenerated images in {reports_dir}:")
                            for img in images[-5:]:  # Show last 5
                                print(f"  - {img}")
                else:
                    print("Invalid selection.")
            except ValueError:
                print("Invalid input.")
        
        elif choice == "3":
            print("\nGenerated visualization files:")
            for file in generated_files:
                file_size = file.stat().st_size
                print(f"  - {file.name} ({file_size} bytes)")
                
                # Show first few lines
                with open(file, 'r', encoding='utf-8') as f:
                    lines = f.readlines()[:5]
                    for line in lines:
                        print(f"      {line.rstrip()}")
                    if len(lines) == 5:
                        print("      ...")
                print()
        
        else:
            print("Invalid choice. Please try again.")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
